import opentype from "opentype.js";

const UNITS_PER_EM = 1000;
const ASCENDER = 800;
const DESCENDER = -200;
const CELL = 200;
const LEFT_BEARING = 50;
const GRID_ROWS = 4;

export function buildOpenTypeFont(project, options = {}) {
  const familyName = sanitizeFamilyName(options.familyName || "Trace Logo");
  const strokeWidth = clamp(Number(options.strokeWidth) || 90, 30, 180);
  const glyphs = [createNotdefGlyph(strokeWidth)];
  const sourceGlyphs = new Map(
    (project.glyphs || [])
      .filter((glyph) => glyph && typeof glyph.char === "string")
      .map((glyph) => [glyph.char, glyph])
  );

  const exportedChars = new Set();
  for (const glyph of sourceGlyphs.values()) {
    if (isHan(glyph.char) || glyph.status !== "完成" || !hasMarks(glyph)) continue;
    addGlyph(glyphs, exportedChars, glyph.char, glyph, strokeWidth);
  }

  addGlyphAlias(glyphs, exportedChars, "〜", "～", sourceGlyphs, strokeWidth);
  addSpaceGlyph(glyphs, exportedChars, " ", 2 * CELL);
  addSpaceGlyph(glyphs, exportedChars, "　", 3 * CELL);
  addComposedKanaGlyphs(glyphs, exportedChars, sourceGlyphs, strokeWidth);
  addCombiningKanaMarks(glyphs, exportedChars, sourceGlyphs, strokeWidth);

  const font = new opentype.Font({
    familyName,
    styleName: "Regular",
    unitsPerEm: UNITS_PER_EM,
    ascender: ASCENDER,
    descender: DESCENDER,
    glyphs
  });
  font.names.version = { en: "Version 0.1" };
  font.names.description = { en: "Generated by Trace Logo Editor" };
  font.names.designer = { en: "Trace Logo Editor" };

  return {
    buffer: Buffer.from(font.toArrayBuffer()),
    familyName,
    filename: `${slugify(familyName)}.otf`,
    glyphCount: glyphs.length - 1,
    sourceGlyphCount: exportedChars.size
  };
}

function addGlyph(glyphs, exportedChars, char, sourceGlyph, strokeWidth, extra = {}) {
  if (exportedChars.has(char)) return;
  const path = buildGlyphPath(sourceGlyph, strokeWidth, extra);
  glyphs.push(new opentype.Glyph({
    name: glyphName(char),
    unicode: char.codePointAt(0),
    advanceWidth: extra.advanceWidth ?? getAdvanceWidth(char),
    path
  }));
  exportedChars.add(char);
}

function addSpaceGlyph(glyphs, exportedChars, char, advanceWidth) {
  if (exportedChars.has(char)) return;
  glyphs.push(new opentype.Glyph({
    name: glyphName(char),
    unicode: char.codePointAt(0),
    advanceWidth,
    path: new opentype.Path()
  }));
  exportedChars.add(char);
}

function addGlyphAlias(glyphs, exportedChars, char, sourceChar, sourceGlyphs, strokeWidth) {
  if (exportedChars.has(char)) return;
  const source = sourceGlyphs.get(sourceChar);
  if (!source || source.status !== "完成" || !hasMarks(source)) return;
  addGlyph(glyphs, exportedChars, char, source, strokeWidth, {
    advanceWidth: getAdvanceWidth(sourceChar)
  });
}

function addComposedKanaGlyphs(glyphs, exportedChars, sourceGlyphs, strokeWidth) {
  const dakuten = sourceGlyphs.get("゛");
  const handakuten = sourceGlyphs.get("゜");
  if (!dakuten && !handakuten) return;

  for (let codePoint = 0x3040; codePoint <= 0x30ff; codePoint += 1) {
    const char = String.fromCodePoint(codePoint);
    const decomposed = Array.from(char.normalize("NFD"));
    if (decomposed.length !== 2) continue;
    const [baseChar, mark] = decomposed;
    const base = sourceGlyphs.get(baseChar);
    const markGlyph = mark === "\u3099" ? dakuten : mark === "\u309a" ? handakuten : null;
    if (!base || !markGlyph || !hasMarks(base) || !hasMarks(markGlyph)) continue;

    const path = buildGlyphPath(base, strokeWidth);
    appendGlyphMarks(path, markGlyph, strokeWidth, { shiftXCells: 2 });
    glyphs.push(new opentype.Glyph({
      name: glyphName(char),
      unicode: codePoint,
      advanceWidth: 4 * CELL,
      path
    }));
    exportedChars.add(char);
  }
}

function addCombiningKanaMarks(glyphs, exportedChars, sourceGlyphs, strokeWidth) {
  for (const [char, sourceChar] of [["\u3099", "゛"], ["\u309a", "゜"]]) {
    const source = sourceGlyphs.get(sourceChar);
    if (!source || !hasMarks(source) || exportedChars.has(char)) continue;
    addGlyph(glyphs, exportedChars, char, source, strokeWidth, {
      shiftXCells: -1.75,
      advanceWidth: 0
    });
  }
}

function buildGlyphPath(glyph, strokeWidth, options = {}) {
  const path = new opentype.Path();
  appendGlyphMarks(path, glyph, strokeWidth, options);
  return path;
}

function appendGlyphMarks(path, glyph, strokeWidth, options = {}) {
  const shiftXCells = Number(options.shiftXCells) || 0;
  const shiftYCells = Number(options.shiftYCells) || 0;
  const latinDrop = /^[a-z]$/.test(glyph.char) ? 1 : 0;

  for (const edgeId of glyph.activeEdges || []) {
    const edge = parseEdge(edgeId);
    if (!edge) continue;
    appendSquareStroke(path, {
      x1: fontX(edge.x1 + shiftXCells),
      y1: fontY(edge.y1 + shiftYCells + latinDrop),
      x2: fontX(edge.x2 + shiftXCells),
      y2: fontY(edge.y2 + shiftYCells + latinDrop)
    }, strokeWidth);
  }

  for (const pointId of glyph.activePoints || []) {
    const point = parsePoint(pointId);
    if (!point) continue;
    appendCircle(
      path,
      fontX(point.x + shiftXCells),
      fontY(point.y + shiftYCells + latinDrop),
      strokeWidth * 0.42
    );
  }
}

function appendSquareStroke(path, edge, strokeWidth) {
  const dx = edge.x2 - edge.x1;
  const dy = edge.y2 - edge.y1;
  const length = Math.hypot(dx, dy);
  if (!length) return;
  const half = strokeWidth / 2;
  const ux = dx / length;
  const uy = dy / length;
  const px = -uy * half;
  const py = ux * half;
  const ex = ux * half;
  const ey = uy * half;
  const points = [
    [edge.x1 - ex + px, edge.y1 - ey + py],
    [edge.x1 - ex - px, edge.y1 - ey - py],
    [edge.x2 + ex - px, edge.y2 + ey - py],
    [edge.x2 + ex + px, edge.y2 + ey + py]
  ];
  path.moveTo(points[0][0], points[0][1]);
  for (let index = 1; index < points.length; index += 1) path.lineTo(points[index][0], points[index][1]);
  path.close();
}

function appendCircle(path, cx, cy, radius) {
  const k = radius * 0.5522847498;
  path.moveTo(cx + radius, cy);
  path.curveTo(cx + radius, cy + k, cx + k, cy + radius, cx, cy + radius);
  path.curveTo(cx - k, cy + radius, cx - radius, cy + k, cx - radius, cy);
  path.curveTo(cx - radius, cy - k, cx - k, cy - radius, cx, cy - radius);
  path.curveTo(cx + k, cy - radius, cx + radius, cy - k, cx + radius, cy);
  path.close();
}

function createNotdefGlyph(strokeWidth) {
  const path = new opentype.Path();
  appendSquareStroke(path, { x1: 100, y1: 0, x2: 100, y2: 700 }, strokeWidth);
  appendSquareStroke(path, { x1: 100, y1: 700, x2: 600, y2: 700 }, strokeWidth);
  appendSquareStroke(path, { x1: 600, y1: 700, x2: 600, y2: 0 }, strokeWidth);
  appendSquareStroke(path, { x1: 600, y1: 0, x2: 100, y2: 0 }, strokeWidth);
  return new opentype.Glyph({ name: ".notdef", advanceWidth: 700, path });
}

function parseEdge(id) {
  let match = /^h-(\d+)-(\d+)$/.exec(id);
  if (match) return { x1: +match[1], y1: +match[2], x2: +match[1] + 1, y2: +match[2] };
  match = /^v-(\d+)-(\d+)$/.exec(id);
  if (match) return { x1: +match[1], y1: +match[2], x2: +match[1], y2: +match[2] + 1 };
  match = /^d1-(\d+)-(\d+)$/.exec(id);
  if (match) return { x1: +match[1], y1: +match[2], x2: +match[1] + 1, y2: +match[2] + 1 };
  match = /^d2-(\d+)-(\d+)$/.exec(id);
  if (match) return { x1: +match[1] + 1, y1: +match[2], x2: +match[1], y2: +match[2] + 1 };
  return null;
}

function parsePoint(id) {
  const match = /^p-(\d+)-(\d+)$/.exec(id);
  return match ? { x: +match[1], y: +match[2] } : null;
}

function getAdvanceWidth(char) {
  if (/\p{Script=Han}/u.test(char)) return UNITS_PER_EM;
  if (/^[a-z0-9]$/.test(char) || /\p{Script=Katakana}/u.test(char)) return 3 * CELL;
  if (/^[\x21-\x7e]$/.test(char) && !/^[A-Z]$/.test(char)) return 3 * CELL;
  return 4 * CELL;
}

function glyphName(char) {
  const code = char.codePointAt(0).toString(16).toUpperCase().padStart(4, "0");
  return `uni${code}`;
}

function fontX(x) {
  return LEFT_BEARING + x * CELL;
}

function fontY(y) {
  return ASCENDER - y * CELL;
}

function hasMarks(glyph) {
  return (glyph.activeEdges?.length || 0) + (glyph.activePoints?.length || 0) > 0;
}

function isHan(char) {
  return /\p{Script=Han}/u.test(char);
}

function sanitizeFamilyName(value) {
  const cleaned = String(value).replace(/[\x00-\x1f<>:"/\\|?*]/g, " ").replace(/\s+/g, " ").trim();
  return cleaned.slice(0, 48) || "Trace Logo";
}

function slugify(value) {
  return value.replace(/[^A-Za-z0-9_-]+/g, "-").replace(/^-+|-+$/g, "") || "trace-logo";
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}
